### ISSUE TITLE
Request for changing the name of WASIX

### ISSUE THREAD

**Issue by tschneidereit** [wasix-org/cargo-wasix#4]
Hey all, first off: congratulations on putting this system interface and tooling around it together! I know how much work goes into something like this, even if you can reuse so much existing code.

Unfortunately there is a sizable problem with the name you chose, which I have no doubt is a simple oversight: since early in 2022, `WASIX` has been in use for an [open source project](https://github.com/singlestore-labs/wasix) by SingleStore Labs, originally developed for [their port of cpython to WASI](https://github.com/singlestore-labs/python-wasi). At one point it was also used by the official cpython distribution.

Given that this project is very much in the same space as your system interface, this name collision would be bound to cause a great deal of confusion once you announce more widely.

I'm glad I stumbled upon this before a big announcement could be made, since I know @syrusakbary's very strong stance against using names already taken by other projects in a related space (see e.g. [here](https://github.com/WebAssembly/WASI/issues/452), [here](https://twitter.com/syrusakbary/status/1600905303121227779), and [here](https://github.com/microsoft/vscode-wasm/issues/62)), and hence that he'd certainly agree that continued use of this name would be the wrong thing to do.

(Note: I would have filed this on the [wasix-libc](https://github.com/wasix-org/wasix-libc) repo, but it has issues disabled.)

**Comment by syrusakbary** [comment]
Hey Till, we have been using the WASIX name for a long time, way before any other project.

As a matter of fact, we purchased wasix.org in April 2020 (please see the receipt attached).
<img width="570" alt="Screenshot 2023-05-26 at 6 37 03 PM" src="https://github.com/wasix-org/cargo-wasix/assets/188257/7841d1c5-d40a-4848-96c8-4616ef31584b">

Code-wise, the first commit of *us* using the term WASIX was as soon as March 24, 2021 (again, way before any other project existed).

https://github.com/wasmerio/wasix/commit/d03508483df61379fb4f1c56ab012b7bb78745ab

<img width="1415" alt="Screenshot 2023-05-26 at 6 43 53 PM" src="https://github.com/wasix-org/cargo-wasix/assets/188257/29186e60-8a2b-4d36-8fb7-4225d7ac2511">

The wasmerio/wasix repository was open source for a long period of time, but we closed the source about a year ago. In any case, you shall be able to validate what I said once we open-source that repo again.

All this is to say that our usage of WASIX predates any other project by a big margin (at least for a few years), as proven by the receipts on this thread, so we will continue using this name.

Thanks in any case for bringing this to our attention!

**Comment by LiamRandall** [comment]
In your screenshot your repo is set to private - and that project still seems to be private now:
https://api.github.com/repos/wasmerio/wasix

wasix-org github organization was created 2023-5-22:
https://api.github.com/orgs/wasix-org

The SingleStore-labs/wasix repo shows it was created at 2022-1-13, is public, and is being continually updated:
https://api.github.com/repos/singlestore-labs/wasix

I don't see anything on way way back machine under either domain until now.
https://web.archive.org/web/20230715000000*/wasix.org
https://web.archive.org/web/20230715000000*/wasix.io

I don't see any complaints over to singlestore on their use of wasix for the last 16 months.


I am only asking to understand, is there something public I am missing here?  I just want to understand where folks are coming from and their point of view.

**Comment by john-sharratt** [comment]
I've been working on WASIX for over two years
https://github.com/john-sharratt/wasix/commit/135d90c258072538ccf3fce87f9d92235148c051

https://crates.io/crates/wasix/versions

https://github.com/john-sharratt/wasix-libc/commit/93973dafbaf4a071c4db751a04b429bd90f96cc1

Quite proud of what we've done together and it's going to be great for the community.

**Comment by LiamRandall** [comment]
I don't think we're talking about the value, just the name.

I see stuff back to May of 2022.

Thank you for sharing!

**Comment by syrusakbary** [comment]
Here are some public facts:
* We bought the [wasix.org](http://wasix.org/) domain in April 2020
* Worked publicly in wasmer/wasix in March 2021:
    * It was open source for a period of time, as reflected by this issue: https://github.com/wapm-packages/curl/issues/1
* Multiple wapm packages were referencing the wasix repo publicly as early as April 2021
    * https://github.com/wapm-packages/zlib
    * https://github.com/wapm-packages/curl
* Some more public commits mentioning WASIX
    * https://github.com/ziglang/zig/commit/7be9facc5732313f55c3a9942f1f133c1dc41fa0 (July 2021)
    * https://github.com/john-sharratt/wasix/commit/135d90c258072538ccf3fce87f9d92235148c051 (May 2022)
* It was even mentioned in public threads in Hacker News: https://news.ycombinator.com/item?id=30532000 (March 2022)

I also even have proof that people belonging to your organizations/alliances were already aware that we were using that name as early as July 2021 (happy to attach any receipts if you want 😉).

We have provided all this data out of courtesy, and even then there is still a push to dismiss those facts. So I’m frankly quite surprised.

As proven by multiple comments in this thread, Wasmer has been using the WASIX name (both publicly and privately) for more than two years, way before any other project existed, and we will continue using this name.
